FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS builder
ENV APP Ruby.Microservices.Notification
ENV PATH="$PATH:/root/.dotnet/tools"

ARG SONAR_PROJECT_KEY=notification-service
ARG SONAR_HOST_URL=http://sonarqube-sonarqube.default.svc.cluster.local:9000
ARG SONAR_TOKEN=1b8f2a7b1cea7e6883a8efcdd9799d643bb63d20

WORKDIR /app

RUN apt-get update && apt-get install -y openjdk-8-jre && \
    dotnet tool install --global dotnet-sonarscanner
    
COPY . ./
RUN dotnet nuget locals --clear all && \
    cd ${APP} && \
    dotnet sonarscanner begin \
    /k:"$SONAR_PROJECT_KEY" \
    /d:sonar.host.url="$SONAR_HOST_URL" \
    /d:sonar.login="$SONAR_TOKEN"

RUN dotnet restore ./${APP}.sln && \
    cd ${APP} && \
    dotnet build ${APP}.csproj && \
    dotnet publish -c Release -o /app/${APP}/out/ && \
    dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" && \
    cp -fr $HOME/.nuget /app/${APP}/out/
    
#    cd ../${APP}.Tests && \
#    dotnet test && \
#    cd ../${APP} && \
#----------------------------------------------------------------

FROM mcr.microsoft.com/dotnet/core/runtime:2.1
ENV APP Ruby.Microservices.Notification
WORKDIR /app
    
COPY --from=builder /app/${APP}/out/ . 
#COPY bin/Docker .
RUN mv -f .nuget/ /root/.nuget
ENTRYPOINT ["dotnet", "Ruby.Microservices.Notification.dll"]
