FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS builder
ENV APP Ruby.Microservices.Spoofing.RabbitMQ
WORKDIR /app

COPY . ./
RUN dotnet nuget locals --clear all 
    #&& \
    #cp -fr Common ../Common && \
    #cp -fr Models ../Models && \
    #cp -fr CoreApps ../CoreApps
    
RUN dotnet restore ./Ruby.Microservices.Spoofing.RabbitMQ.sln && \
    cd ${APP} && \
    dotnet build ${APP}.csproj && \
    dotnet publish -c Release -o /app/${APP}/out/ && \
    cp -fr $HOME/.nuget /app/${APP}/out/
#----------------------------------------------------------------

FROM mcr.microsoft.com/dotnet/core/runtime:2.1
ENV APP Ruby.Microservices.Spoofing.RabbitMQ
WORKDIR /app

ADD https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64 /usr/local/bin/confd
RUN chmod +x /usr/local/bin/confd

COPY Ruby.Microservices.Spoofing.RabbitMQ/confd /etc/confd
RUN apt-get update && apt-get install -y dos2unix && \
    find /etc/confd -type f | xargs dos2unix && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/* && \
    chmod +x /etc/confd/start.sh

COPY --from=builder /app/${APP}/out/ . 
RUN mv -f .nuget/ /root/.nuget
ENTRYPOINT ["/etc/confd/start.sh"]
