FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS builder
ENV APP Ruby.Identity
WORKDIR /app

COPY . ./
RUN dotnet nuget locals --clear all

RUN dotnet restore ./${APP}.sln && \
    cd src/${APP}.Service && \
    dotnet build ${APP}.Service.csproj && \
    cd ../${APP}.Service.Unit.Tests && \
    dotnet test && \
    cd ../${APP}.Service && \    
    dotnet publish -c Release -o /app/${APP}/out/ && \
    cp -fr $HOME/.nuget /app/${APP}/out/
#----------------------------------------------------------------

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
ENV APP Ruby.Identity
WORKDIR /app

ADD https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64 /usr/local/bin/confd
COPY src/${APP}.Service/confd /etc/confd
RUN chmod +x /etc/confd/start.sh && \
    apt-get update && apt-get install -y dos2unix && \
    find /etc/confd -type f | xargs dos2unix && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/* && \
    chmod +x /usr/local/bin/confd

COPY --from=builder /app/${APP}/out/ . 
COPY ssl_cert.pfx .
RUN mv -f .nuget/ /root/.nuget

#https://github.com/dotnet/SqlClient/issues/633
#https://github.com/dotnet/SqlClient/issues/222
#Issue with EF:
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf

ENTRYPOINT ["/etc/confd/start.sh"]
