FROM mono:6.12.0.182
ADD . /src
WORKDIR /src

RUN apt-get update && apt-get install mono-4.0-service dos2unix -y

RUN /usr/bin/nuget restore -configFile Nuget.Config && \
    msbuild Ruby.Microservices.CustomerInformationService.RabbitMQ.sln /restore && \
    ls -la /src/Ruby.Microservices.CustomerInformationService.RabbitMQ/bin/Debug
    
ADD https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64 /usr/local/bin/confd

#COPY ${APP}/confd /etc/confd
RUN chmod +x /etc/confd/start.sh && \
    dos2unix /etc/confd/start.sh && \
    rm -rf /var/lib/apt/lists/* && \
    chmod +x /usr/local/bin/confd    

ENTRYPOINT ["/etc/confd/start.sh"]
#CMD [ "mono-service", "/src/Ruby.Microservices.CustomerInformationService.RabbitMQ/bin/Debug/Ruby.Microservices.CustomerInformation.RabbitMQ.exe", "--install", "--no-daemon", "--debug" ]
