FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS builder
ENV APP Ruby.Microservices.Partner.MyCase
WORKDIR /app

COPY . ./
RUN dotnet nuget locals --clear all

RUN dotnet restore ./Ruby.Microservices.Partner.MyCase.sln && \
    cd ${APP} && \
    dotnet build ${APP}.csproj && \
    cd ../${APP}.Test && \
    dotnet test && \
    cd ../${APP} && \    
    dotnet publish -c Release -o /app/${APP}/out/ && \
    cp -fr $HOME/.nuget /app/${APP}/out/
#----------------------------------------------------------------

FROM mcr.microsoft.com/dotnet/core/runtime:2.1
ENV APP Ruby.Microservices.Partner.MyCase
ADD https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64 /usr/local/bin/confd
RUN chmod +x /usr/local/bin/confd

COPY confd /etc/confd
RUN apt-get update && apt-get install -y dos2unix
RUN find /etc/confd -type f | xargs dos2unix && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*
RUN chmod +x /etc/confd/start.sh

WORKDIR /app
COPY --from=builder /app/${APP}/out/ .

ENTRYPOINT ["/etc/confd/start.sh"]
