FROM mono:6.12.0.182
ADD . /src
WORKDIR /src

RUN apt-get update && apt-get install mono-4.0-service -y

RUN mono nuget.exe restore -configFile Nuget.Config && \
    msbuild Ruby.Microservices.CustomerInformationService.RabbitMQ.sln /restore && \
    ls -la /src/Ruby.Microservices.CustomerInformationService.RabbitMQ/bin/Debug

CMD [ "mono-service", "/src/Ruby.Microservices.CustomerInformationService.RabbitMQ/bin/Debug/Ruby.Microservices.CustomerInformation.RabbitMQ.exe", "--install", "--no-daemon" ]
