FROM mono:6.12.0.182
ADD . /app
WORKDIR /app

ADD https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64 /usr/local/bin/confd
COPY Ruby.Microservices.Partner.Salesforce.RabbitMQ/confd /etc/confd

RUN apt-get update && apt-get install mono-4.0-service dos2unix -y && \
    /usr/bin/nuget restore -config Nuget.Config Ruby.Microservices.PartnerAPI.Salesforce.RabbitMQ.sln && \
    msbuild Ruby.Microservices.PartnerAPI.Salesforce.RabbitMQ.sln /restore && \
    ls -la /app/Ruby.Microservices.PartnerAPI.Salesforce.RabbitMQ/bin/Debug
    
RUN chmod +x /etc/confd/start.sh && \
    chmod +x /usr/local/bin/confd && \ 
    dos2unix /etc/confd/start.sh && \
    rm -rf /var/lib/apt/lists/*    

ENTRYPOINT ["/etc/confd/start.sh"]
