FROM mono
ADD . /src
WORKDIR /src

RUN mono nuget.exe restore -configFile Nuget.Config && \
    msbuild Ruby.Microservices.CustomerInformationService.RabbitMQ.sln /restore && \
    ls -la /src/Ruby.Microservices.CustomerInformationService.RabbitMQ/bin/Debug

CMD [ "mono-service", "/src/Ruby.Microservices.CustomerInformationService.RabbitMQ/bin/Debug/Ruby.Microservices.CustomerInformation.RabbitMQ.exe","--no-daemon" ]
