name: Check difference options

on:
  workflow_dispatch:
    inputs:
      source:
        type: choice
        description: First environment source to compare
        options: 
        - QA1
        - QA2
        - QA3
        - QA4
        - QA5
        - QA6        
      destination:
        type: choice
        description: Second environment source to compare
        options: 
        - QA1
        - QA2
        - QA3
        - QA4
        - QA5
        - QA6        
jobs:
  init:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: LouisBrunner/diff-action@v0.1.0
        with:
          old: ${{ github.event.inputs.source }}.md
          new: ${{ github.event.inputs.destination }}.md
          mode: addition
          tolerance: mixed-worse
