name: PR environment Deployer
on:
  pull_request:
    types:
      - labeled
jobs:
  label:
    name: Run only when the labels include "QA"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'QA') }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "${{ toJson(github.event.pull_request.labels) }}"
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
          for label in ${{ toJson(github.event.pull_request.labels.*.name) }}; do
            echo $label
          done
