name: PR environment deployer

on:
  pull_request:
    types: [labeled, opened, edited]

jobs:
  enforce-kind:
    name: Pr environment deployer
    runs-on: ubuntu-latest
    steps:
      - name: Check if a valid Environment is set
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          if jq --exit-status 'any(test("environment/qa1") or test("environment/qa2") or test("environment/qa3") or test("environment/qa4") or test("environment/qa5") or test("environment/qa6"))' >/dev/null <<< $LABELS; then
            echo "::error ::Please set environment/ENVIRONMENT_NAME as label"
            echo $LABELS
            exit 1
          else
            echo $LABELS
          fi
