name: Cleanup old branches
on:
  workflow_call:
    secrets:
      PAT:
        required: true  
  
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.6
        with:
          repo_token: ${{ secrets.PAT }}
          date: '3 months ago'
          dry_run: false #true
          delete_tags: true
          minimum_tags: 1
          extra_protected_branch_regex: ^(release|main|master)$
