on: [workflow_dispatch]

name: Clean log & history

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest #Uncomment if it has to be run on a public Agent
    steps:
    - uses: actions/checkout@v2.0.0

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: (GLOBAL) Configure Service name.
      run: |
        git config user.email "check-action@github"
        git config user.name "check-action"	  
        tfile=$(mktemp /tmp/config.XXXXXXXXX)
        GITCONF=".git/config"
        commitmsg=${1:-git repository initialised}
        if [ -f "$GITCONF" ]; then
          mv "$GITCONF" tfile
          rm -rf .git
          git init .
          mv tfile "$GITCONF"
          git add .
          git commit -a -m "${commitmsg}"
          git push -f --set-upstream origin master
        else
          echo "Warning: No git config file found. Aborting.";exit;
        fi
