name: 'Env tester'

on:
  workflow_dispatch:

jobs:   
  Deploy:
    name: 'Choose an environment'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA1
      env:
        name: QA1   
      id: QA1
      run: |
        pwd
        echo "test1"
        
    - name: Deploy to QA2
      id: QA2
      env:
        name: QA2      
      run: |
        pwd
        echo "test2"
      continue-on-error: true
  
    - name: Deploy to PROD
      id: PROD
      env:
        name: PROD      
      run: |
        pwd
        echo "prod"
      continue-on-error: true
  
