name: 'Env tester'

on:
  workflow_dispatch: #workflow_call:
    inputs:
      Environment:
        description: 'Environment where has to be deployed'
        type: choice
        required: true
        options: 
        - qa1
        - qa2
        - qa3
        - qa4
        - qa5
        - qa6
      Tag:
        description: 'Image Tag be deployed Qa1-Qa6'
        type: string
        required: true
        default: ''
      secrets:
      PAT:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true
      EKS_SERVICE:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      PFX_CERT:
        required: true
      SSL_PEM_CERT:
        required: true
      SSL_PEM_KEY:
        required: true
      NUGET_CONFIG:
        required: true

jobs:   
  DeployQA1:
    name: 'QA1'
    runs-on: ubuntu-latest
    environment:
      name: QA1    
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA1  
      id: QA1
      run: |
        pwd
        echo "QA1"
        

  DeployQA2:
    name: 'QA2'
    runs-on: ubuntu-latest
    #needs: DeployQA1
    environment:
      name: QA2    
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA2
      id: QA2
      run: |
        pwd
        echo "QA2"
        

  DeployQA3:
    name: 'QA3'
    runs-on: ubuntu-latest
    #needs: [DeployQA1,DeployQA2]
    environment:
      name: QA3    
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA3
      id: QA3
      run: |
        pwd
        echo "QA3"

  DeployQA4:
    name: 'QA4'
    runs-on: ubuntu-latest
    #needs: [DeployQA1,DeployQA2,DeployQA3]
    environment:
      name: QA4    
    defaults:
      run:
        shell: bash

    steps:     
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA4
      id: QA4
      run: |
        pwd
        echo "QA4"
        
  DeployQA5:
    name: 'QA5'
    runs-on: ubuntu-latest
    #needs: [DeployQA1,DeployQA2,DeployQA3,DeployQA4]
    environment:
      name: QA5
    defaults:
      run:
        shell: bash

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA5
      id: QA5
      run: |
        pwd
        echo "QA5"
        
  DeployQA6:
    name: 'QA6'
    runs-on: ubuntu-latest
    needs: [DeployQA1,DeployQA2,DeployQA3,DeployQA4,DeployQA5]
    environment:
      name: QA6    
    defaults:
      run:
        shell: bash

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA6
      id: QA6
      run: |
        pwd
        echo "QA6"        

  DeployPROD:
    name: 'PROD'
    runs-on: ubuntu-latest
    needs: [DeployQA1,DeployQA2,DeployQA3,DeployQA4,DeployQA5,DeployQA6]
    environment:
      name: PROD    
    defaults:
      run:
        shell: bash

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to PROD  
      id: PROD
      run: |
        pwd
        echo "PROD"        
