name: Update App to the Selected Environment.

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment where has to be deployed [1] Qa1, [2] Qa2, [3] Qa3, [4] Qa4, [5] Qa5, [6] Qa6'
        required: true
        default: '1'
      Tag:
        description: 'Image Tag be deployed Qa1-Qa6'
        required: true
        default: ''
      
jobs:
  init:
    runs-on: self-hosted
    #runs-on: ubuntu-latest #Uncomment if it has to be run on a public Agent

    steps:
    - uses: actions/checkout@v2.0.0

    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
         continue-after-seconds: 500 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: (GLOBAL) Configure Service name.
      run: |
        echo "EKS_SERVICE=${{secrets.EKS_SERVICE}}" >> $GITHUB_ENV        

    - name: (GLOBAL) Debug
      run: |
        echo "Environment: ${{github.event.inputs.Environment}}"
        
    - name: (GLOBAL) Check out ruby-apps-deploy repository
      uses: actions/checkout@master
      with:
        token: ${{ secrets.PAT }}
        repository: callruby/ruby-apps-deploy
        path: ruby-apps-deploy
        ref: 'master'        

    - uses: imranismail/setup-kustomize@v1
    
    - name: (DEV) Update Tag - Deploy to EKS through ArgoCD
      id: UpdateTag
      run: |
        echo "===================================="
        echo "DEBUG:"
        echo "IMAGE_TAG: ${{github.event.inputs.Tag}}"
        echo "EKS_SERVICE: ${EKS_SERVICE}"
        echo "===================================="
        ECR_REPO=425300134585.dkr.ecr.us-west-1.amazonaws.com
        if [[ "${{ github.event.inputs.Environment }}" == "1" ]]; then
          ENV=qa1
        fi
        if [[ "${{ github.event.inputs.Environment }}" == "2" ]]; then
          ENV=qa2
        fi
        if [[ "${{ github.event.inputs.Environment }}" == "3" ]]; then
          ENV=qa3
        fi
        if [[ "${{ github.event.inputs.Environment }}" == "4" ]]; then
          ENV=qa4
        fi
        if [[ "${{ github.event.inputs.Environment }}" == "5" ]]; then
          ENV=qa5
        fi
        if [[ "${{ github.event.inputs.Environment }}" == "6" ]]; then
          ENV=qa6
        fi
        if [[ -z "$ENV" ]]; then
          echo "============================================================================================"
          echo "Environment ${{ github.event.inputs.Environment }} is not supported to deploy it in this way"
          echo "============================================================================================"
          exit 1
        else
          echo "============================================================================================"
          echo "Environment: $ENV"
          echo "============================================================================================"
        fi
        ls -la ruby-apps-deploy
        cd ruby-apps-deploy/helm/$ENV/$EKS_SERVICE
        ls -la
        sed -i -e "s|image:.*|image: $ECR_REPO/${EKS_SERVICE}:${{github.event.inputs.Tag}}|g" values.yaml
        cat values.yaml
        git config user.email "check-action@github"
        git config user.name "check-action"
        git pull
        #git add kustomization.yml
        git add values.yaml
        git commit -m "Update ${EKS_SERVICE} image to ${{github.event.inputs.Tag}} on deploy folder/file $ENV"
        set +e
        git push origin master > error 
        cat error
        if [[ $(cat error | grep -c "error" ) -eq 1 ]]; then
          echo "========================================================"
          echo "Retrying...."
          echo "========================================================"
          set -e
          sleep 5
          git pull
          git commit -m "Update ${EKS_SERVICE} image to ${{github.event.inputs.Tag}} on deploy folder/file $ENV"
          git push origin master
        fi 
    - name: Checkout code
      uses: actions/checkout@v2
