name: 'Env tester'

on:
  workflow_dispatch:

jobs:   
  DeployQA1:
    name: 'QA1'
    runs-on: ubuntu-latest
    environment:
      name: QA1    
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA1  
      id: QA1
      run: |
        pwd
        echo "QA1"
        

  DeployQA2:
    name: 'QA2'
    runs-on: ubuntu-latest
    needs: DeployQA1
    environment:
      name: QA2    
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to QA2
      id: QA2
      run: |
        pwd
        echo "QA2"
        

  DeployPROD:
    name: 'PROD'
    runs-on: ubuntu-latest
    needs: [DeployQA1,DeployQA2]
    environment:
      name: PROD    
    defaults:
      run:
        shell: bash

    steps:
                
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Deploy to PROD  
      id: PROD
      run: |
        pwd
        echo "test1"        
