name: Closed Pull request checks
on:
  #push:
    #branches: 
      #- pr*
  pull_request:
    types: [ closed ] 
 
env:
  REPOSITORY: "ruby-apps-deploy"
  REPOSITORY_PROJECT: "ruby-project-deploy"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        ref: ${{ github.event.pull_request.base.sha }}

    - name: Get short SHA
      id: slug
      run: |
        echo "COMMIT=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo ${{ github.event.pull_request.head.sha }} | cut -c1-7
        
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
         continue-after-seconds: 500 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: (GLOBAL) Check out ${{env.REPOSITORY}} repository
      uses: actions/checkout@master
      with:
        token: ${{ secrets.PAT }}
        repository: callruby/${{env.REPOSITORY}}
        path: ${{env.REPOSITORY}}
        ref: 'master'
                  
    - name: (GLOBAL) Debug
      run: |
        echo "EKS_SERVICE=${{secrets.EKS_SERVICE}}" >> $GITHUB_ENV
        
    - name: (GLOBAL) Check out ruby-project-deploy repository
      uses: actions/checkout@master
      with:
        token: ${{ secrets.PAT }}
        repository: callruby/ruby-project-deploy
        path: ruby-project-deploy
        ref: 'master'
        
    - name: (DEV) Delete app version on Project Repository
      id: UpdateTagPR
      run: |
        echo "===================================="
        echo "DEBUG:"
        echo "ECR_REPOSITORY: ${EKS_SERVICE}"
        echo "IMAGE_TAG: $COMMIT"
        echo "EKS_SERVICE: ${EKS_SERVICE}"
        echo "===================================="
        cd ruby-project-deploy
        rm -f apps/dev-pr/$EKS_SERVICE-${COMMIT}.yaml
        git config user.email "check-action@github"
        git config user.name "check-action"
        git add apps/dev-pr/*
        git commit -am "Deleted ${EKS_SERVICE}-${COMMIT} - PR application"
        git push origin master        
    - name: Checkout code
      uses: actions/checkout@v2
