name: Zuora Webapi Service Workflow Sync

on: [workflow_dispatch]
env:
  DRY_RUN: false
  REPOSITORIES: |
    callruby/zuora-webapi@release
    
  WORKFLOW_FILES: |
    main_feature_branch.yaml=main_feature_branch.yaml
    main_manual_ecr_checks_reusable.yaml=main_manual_ecr_checks_reusable.yaml
    use_clean_workflows_reusable.yaml=use_clean_workflows_reusable.yaml
    use_issue_comments_reusable.yaml=use_issue_comments_reusable.yaml
    use_main_external_dockerfile_reusable.yaml=use_main_external_dockerfile_reusable.yaml
    use_main_pr_labels_reusable.yaml=use_main_pr_labels_reusable.yaml
    use_clean_old_commits_reusable.yaml=use_clean_old_commits_reusable.yaml
    main_prod_manual_tag.yaml=main_prod_manual_tag.yaml
    main_branch_updated.yaml=main_branch_updated.yaml
        
jobs:
  Github_Workflow_Sync:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          PULL_REQUEST: true
          AUTO_CREATE_NEW_BRANCH: false
