name: MariaDB Check liquibase changelog files

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.4
        ports:
          - 3306/tcp
        env:
          #MYSQL_USER: root
          #MYSQL_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10   
    
    steps:
    - uses: actions/checkout@v2.0.0
        
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
         continue-after-seconds: 500 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Wait for MariaDB and Install Liquibase
      run: |
        sudo apt update
        LIQUIBASE_VERSION=3.5.3
        LIQUIBASE_PREFIX=/usr/local/lib
        LIQUIBASE_BIN=/usr/local/bin
        JDBC_MYSQL_VERSION=1.5.7
        sudo apt install -y default-jre
        sudo rm -rf ${LIQUIBASE_PREFIX}/liquibase
        sudo rm -f ${LIQUIBASE_BIN}/liquibase
        sudo mkdir -p ${LIQUIBASE_PREFIX}/liquibase
        sudo curl -o /tmp/liquibase-${LIQUIBASE_VERSION}.tar.gz -sSL https://github.com/liquibase/liquibase/releases/download/liquibase-parent-${LIQUIBASE_VERSION}/liquibase-${LIQUIBASE_VERSION}-bin.tar.gz
        sudo tar -zxf /tmp/liquibase-${LIQUIBASE_VERSION}.tar.gz -C ${LIQUIBASE_PREFIX}/liquibase
        #sed -i "s|bash$|ash|" ${LIQUIBASE_PREFIX}/liquibase/liquibase
        sudo chmod +x ${LIQUIBASE_PREFIX}/liquibase/liquibase
        sudo ln -s ${LIQUIBASE_PREFIX}/liquibase/liquibase ${LIQUIBASE_BIN}
        sudo curl -o ${LIQUIBASE_PREFIX}/liquibase/lib/mariadb-${JDBC_MYSQL_VERSION}.jar -sSL https://downloads.mariadb.com/Connectors/java/connector-java-${JDBC_MYSQL_VERSION}/mariadb-java-client-${JDBC_MYSQL_VERSION}.jar        
        sudo curl -fSL https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.38.tar.gz -o /tmp/mysql.tgz
        sudo mkdir -p /tmp/mysql
        sudo tar -xvf /tmp/mysql.tgz -C /tmp/mysql --strip-components=1
        sudo cp /tmp/mysql/*.jar /usr/local/lib/liquibase/lib

    - name: Execute Liquibase
      run: |
        sudo /usr/local/bin/liquibase --url=jdbc:mariadb://127.0.0.1:${{ job.services.mariadb.ports[3306] }}/test?autoReconnect=true"&"useSSL=false --changeLogFile=changelog/changelog.xml --username=root --password=root --logLevel=INFO update

    - name: Checkout code
      uses: actions/checkout@v2
