name: Auto approve pipeline changes

on:
  pull_request

jobs:
  auto-approve:
    runs-on: self-hosted
    if: "contains(${{ github.event.pull_request.title }}, 'Files Sync From callruby/ruby-apps-workflows')"
    permissions:
      pull-requests: write
    steps:
        
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'fbuinosquy1985'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
