name: Pull and Push multiple images

on: [workflow_dispatch]
 
env:
  AWS_DEFAULT_REGION: "us-west-1"
  
jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
        
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
         continue-after-seconds: 500 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   #Comment if it has to be run on a public Agent 
    - name: (GLOBAL) Configure AWS credentials using the secrets obtained from Vault
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        #Uncomment if it has to be run on a public Agent    
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: (SHARED) Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1      
        
    - name: (DEV) Pull Push base Images
      id: Deploy
      run: |
        echo "===================================="
        echo "Building Docker Image"
        echo "===================================="
        AWS_ACCOUNT="425300134585"
        AWS_DEFAULT_REGION="us-west-1"
        docker pull busybox:1.32
        docker pull sonarqube:8.5.1-community
        docker pull hashicorp/vault:1.7.0
        docker pull hashicorp/vault:1.7.1
        docker pull gcr.io/google_containers/leader-elector:0.4
        docker pull hashicorp/vault-k8s:0.10.0
        docker pull hashicorp/consul:1.9.4
        docker pull hashicorp/consul-k8s:0.25.0
        docker pull basisai/consul-esm:0.4.0
        docker pull quay.io/argoproj/argocd:v1.8.4
        docker pull ghcr.io/dexidp/dex:v2.30.0
        docker pull ghcr.io/dexidp/dex:v2.27.0
        docker pull quay.io/argoproj/argocd:v2.1.5
        docker pull haproxy:2.0.20-alpine
        docker pull argoprojlabs/argocd-notifications:v1.1.1
        docker pull quay.io/dockernohub/redis:5.0-alpine
        docker tag busybox:1.32 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/busybox:1.3.2
        docker tag sonarqube:8.5.1-community $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sonarqube:8.5.1-community
        docker tag hashicorp/vault:1.7.0 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:1.7.0
        docker tag hashicorp/vault:1.7.1 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:1.7.1
        docker tag gcr.io/google_containers/leader-elector:0.4 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:leader-elector-0.4
        docker tag hashicorp/vault-k8s:0.10.0 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:vault-k8s010
        docker tag hashicorp/consul:1.9.4 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:1.9.4
        docker tag hashicorp/consul-k8s:0.25.0 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:consul-k8s0250
        docker tag basisai/consul-esm:0.4.0 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:consul-esm0.4.0
        docker tag quay.io/argoproj/argocd:v1.8.4 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:1.8.4
        docker tag quay.io/argoproj/argocd:v2.1.5 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:2.1.5
        docker tag quay.io/dexidp/dex:v2.26.0 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:dex2.22.6
        docker tag ghcr.io/dexidp/dex:v2.30.0 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:dex2.30.0
        docker tag argoprojlabs/argocd-notifications:v1.1.1 $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:notifications1.1.1
        docker tag quay.io/dockernohub/redis:5.0-alpine $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:redis5.0
        docker tag haproxy:2.0.20-alpine $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:haproxy2.0.20
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/busybox:1.3.2
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sonarqube:8.5.1-community
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:1.7.0
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:1.7.1
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:vault-k8s010
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:1.9.4
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:consul-k8s0250
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:consul-esm0.4.0
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:1.8.4
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:2.1.5
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:dex2.22.6
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:notifications1.1.1
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:redis5.0
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:dex2.30.0
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd:haproxy2.0.20
        docker push $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault:leader-elector-0.4
                      
    - name: Docker clean up
      run: |
        docker images
        docker rmi $(docker images -q) || true;echo $?                     
                      
    - name: Checkout code
      uses: actions/checkout@v2
