name: Update uptime-status repo trigger dispatch
on:
  push:
    branches: 
      - master
      
jobs:
  release:
    name: Trigger Dispatch Master workflow on Up-time repository
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        
      - name: Sleep till wait for the other pipelines
        if: always()
        run: |
          sleep 180        

      - name: Trigger uptime-status master workflow
        if: always()
        run: |
          curl --request POST -H \"Accept: application/vnd.github.v3+json\" --url 'https://api.github.com/repos/callruby/uptime-status/dispatches' --header 'authorization: Bearer ${{ secrets.GH_PAT }}' --data '{"event_type": "master_update","client_payload": {}'

      - name: Sleep till wait for the other pipelines
        if: always()
        run: |
          sleep 120

      - name: Trigger uptime-status ghpage workflow
        if: always()
        run: |
          curl --request POST -H \"Accept: application/vnd.github.v3+json\" --url 'https://api.github.com/repos/callruby/uptime-status/dispatches' --header 'authorization: Bearer ${{ secrets.GH_PAT }}' --data '{"event_type": "ghpages_update","client_payload": {}'
