name: Use reusable docker pull request open build pipeline

on:
  #push:
    #branches: 
      #- pr*
  pull_request:
    types: [ opened, reopened ]      

jobs:
  do-it:
    runs-on: self-hosted #ubuntu-latest #self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Simple Task
        run: echo Hello, world!

  docker:
    uses: callruby/ruby-apps-workflows/.github/workflows/main_pr_open_reusable.yml@master
    with:
      tag: $GITHUB_RUN_NUMBER
    secrets:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PAT: ${{secrets.PAT}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      EKS_SERVICE: ${{secrets.EKS_SERVICE}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      PFX_CERT: ${{secrets.PFX_CERT}}
      SSL_PEM_CERT: ${{secrets.SSL_PEM_CERT}}
      SSL_PEM_KEY: ${{secrets.SSL_PEM_KEY}}
      NUGET_CONFIG: ${{secrets.NUGET_CONFIG}}
      DEPLOY_TO_ECS: ${{secrets.DEPLOY_TO_ECS}}
      APPROVERS: "" # comma list of users that has to be added as pr reviewers 
