name: Use reusable issue comment pipeline

on:
  issue_comment:
    types:
      - created
      
jobs:
  do-it:
    runs-on: ubuntu-latest #self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Simple Task
        run: echo Hello, world!

  docker:
    uses: callruby/ruby-apps-workflows/.github/workflows/issue_comments_reusable.yaml@master
    with:
      tag: $GITHUB_RUN_NUMBER
    secrets:
      #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PAT: ${{secrets.PAT}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      EKS_SERVICE: ${{secrets.EKS_SERVICE}}
      SHARED_GITHUB_K8S_KUBECONFIG: ${{secrets.SHARED_GITHUB_K8S_KUBECONFIG}}
