name: Use reusable docker pull request open build label pipeline

on:
  pull_request:
    types: [ labeled ]      

jobs:
  do-it:
    runs-on: self-hosted #ubuntu-latest #self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Simple Task
        run: echo Hello, world!

  docker:
    uses: callruby/ruby-apps-workflows/.github/workflows/main_pr_labels_reusable.yaml@master
    with:
      tag: ${{ github.event.pull_request.head.sha }}
    secrets:
      PAT: ${{secrets.PAT}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      EKS_SERVICE: ${{secrets.EKS_SERVICE}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      NUGET_CONFIG: ${{secrets.NUGET_CONFIG}}
      SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}} 
      SLACK_BOT_CHANNEL: ${{secrets.SLACK_BOT_CHANNEL}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      DEPLOY_TO_ECS: ${{secrets.DEPLOY_TO_ECS}}
      ECS_QA_CLUSTER_NAME: ${{secrets.ECS_QA_CLUSTER_NAME}}
      ECS_QA_SERVICE_NAME: ${{secrets.ECS_QA_SERVICE_NAME}}
      S3_OLD_QA_AWS_ACCESS_KEY_ID: ${{secrets.S3_OLD_QA_AWS_ACCESS_KEY_ID}}
      S3_OLD_QA_AWS_SECRET_ACCESS_KEY: ${{secrets.S3_OLD_QA_AWS_SECRET_ACCESS_KEY}}      
