name: Use reusable clean workflow pipeline

on:
  schedule:
  - cron: '0 0 * * *'  # GMT
  workflow_dispatch:
     
jobs:
  do-it:
    runs-on: ubuntu-latest #self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Simple Task
        run: echo Hello, world!

  docker:
    uses: callruby/ruby-apps-workflows/.github/workflows/main_pr_open_reusable.yml@master
    with:
      tag: $GITHUB_RUN_NUMBER
    secrets:
      #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PAT: ${{secrets.PAT}}
